name: Java Detect and Diktat

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect:
    name: Run Detect for security vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Detect
        run: |
          curl -L https://detect.synopsys.com/detect.sh -o detect.sh
          chmod +x detect.sh

      - name: Run Detect for Security Scans
        run: ./detect.sh --detect.source.path=$(pwd)

  diktat:
    name: Run Diktat static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Diktat
        run: |
          curl -s https://dl.bintray.com/diktat/diktat-cli/diktat-cli-1.0.0.jar -o diktat-cli.jar

      - name: Run Diktat for Static Analysis
        run: java -jar diktat-cli.jar --input $(pwd)/src --output diktat-report.json
